// Estado global compartido entre módulos.
// Todos los módulos importan este objeto y lo mutan directamente.
export const state = {
  currentUser: null,
  isAdmin: false,
  proveedores: [],
  contactos: [],
  comisionistas: [],
  camposCustom: [],
  configData: {},
  logoBase64: '',
  currentProvId: null,
  rotuloProvId: null,
  rotuloGuardadoActual: null,
  rotuloEditando: null,
  rotuloFotosGrupoId: null,
  rotuloFotosProvId: null,
  editingUserId: null,
  editingProvId: null,
  editingComId: null,
  contactRowCounter: 0,
  selectedSize: 'a4',
  selectedDesignSize: 'a4',
  rotuloDisenos: [],
  // Tareas Semáforo
  tareas: [],
  currentTaskId: null,
  // Mantenimiento
  mantenimientoOnly: false,
  items: [],
  familias: [],
  subfamilias: [],
  editingItemId: null,
  retiroCart: [],
  historialRetiros: [],
  historialUsuarios: {},
  historialAdmin: false,
  sectores: [],
};
